//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shopping_DBEntities : DbContext
    {
        public Shopping_DBEntities()
            : base("name=Shopping_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_tb> admin_tb { get; set; }
        public virtual DbSet<customer_tb> customer_tb { get; set; }
        public virtual DbSet<supplier_tb> supplier_tb { get; set; }
    }
}
