//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers_tb
    {
        public int Supplier_Id { get; set; }
        public string Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_ID { get; set; }
        public string Address { get; set; }
        public string Govt_ID_Proof { get; set; }
        public string Password { get; set; }
    }
}
