//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_tb
    {
        public int Supplier_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public string Govt__Id_Proof { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
    }
}
